services:
  app:
    container_name: blockchain-gateway-app
    restart: always
    build:
      context: .
      dockerfile: docker/go-blockchain-gateway/go.Dockerfile
      args:
        PORT: ${PUBLIC_HTTP_ADDR}
    image: blockchain-gateway-app:latest
    environment:
      - TZ=Asia/Novosibirsk
    ports:
      - ${PUBLIC_HTTP_ADDR}:${PUBLIC_HTTP_ADDR}
      - ${PRIVATE_GRPC_ADDR}:${PRIVATE_GRPC_ADDR}
    networks:
      - subtrack-net
volumes:
  redis_data:
    name: users-redis_data
networks:
  subtrack-net:
    name: subtrack-net
    driver: bridge